<a href="https://colab.research.google.com/github/OluwatoyosiN/OluwatoyosiN/blob/main/cleaned_Dr_Eckel_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np

In [13]:
from google.colab import files
uploaded= files.upload()

Saving carbon_data.xlsx to carbon_data.xlsx

In [24]:
import io
both1= pd.read_excel(io.BytesIO(uploaded[ "carbon_data.xlsx"]))
both1

,Unnamed: 0,Booking_date,Order_number,Customer_name,Customer_postal_code,Delivery_Country,Customer_Delivery_address_name,Delivery_Postal_Code2,Delivery_country_name,Delivery_Terms,Outgoing_goods_date,Invoice_N,lesser than 3tonnes,Quantity_kg,Shipping_agent,Delivery_Country_,Point_of_pickup,Coordinates,latitude,longitude
0,0,2022-07-20,VKAU-102380,Möhlenkamp GmbH & Co. KG,26901,DE,Möhlenkamp GmbH & Co. KG,26901,DE,DAP,2022-07-20,VRG-102329,True,250.0,HELLMANN,Germany,56651,Deutschland,51.163818,10.447831
1,1,2022-07-21,VKAU-102382,Spezialfutter Neuruppin GmbH & Co. KG,16816,DE,ALB-Futterwerk Antje Lühr,21438,DE,DAP,2022-07-20,NaN,False,NaN,NaN,Germany,56651,Deutschland,51.163818,10.447831
2,2,2022-07-18,VKAU-102379,Hoogland BV,8903 JN,NL,Hoogland BV,8938 AA,NL,DAP,2022-07-22,NaN,False,NaN,NaN,Netherland,56651,"Netherland, Greatland Subdivision, San Pedro, ...",14.351639,121.050114
3,3,2022-07-18,VKAU-102378,Tromp B.V.,8912 AT,NL,Tromp B.V.,8912 AT,NL,DAP,2022-07-27,NaN,False,NaN,NaN,Netherland,56651,"Netherland, Greatland Subdivision, San Pedro, ...",14.351639,121.050114
4,4,2022-07-15,VKAU-102377,Xaver Scheule GmbH,87757,DE,Xaver Scheule GmbH,87757,DE,DAP,2022-07-25,NaN,False,NaN,NaN,Germany,56651,Deutschland,51.163818,10.447831
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2369,2369,2020-04-07,VKAU-100005,TKF Korpas LLC,129515,RU,TKF Korpas LLC,129515,RU,FCA,2020-04-07,VRG-100027,True,1000.0,NaN,Russia,56651,Россия,64.686314,97.745306
2370,2370,2020-04-17,VKAU-100004,Kubbar International Company,11936,EG,Kubbar International Company,11936,EG,CIF,2020-04-17,VRG-100054,True,0.0,NaN,Egypt,56651,مصر,26.254049,29.267547
2371,2371,2020-04-30,VKAU-100003,EugeneBio,16697,KR,EugeneBio,16697,KR,CIF,2020-04-30,VRG-100098,False,10000.0,LESCHACO,Korea,56651,대한민국,36.638392,127.696119
2372,2372,2020-04-27,VKAU-100002,Trouw Nutrition Deutschland GmbH,86666,DE,Trouw Nutrition Deutschland GmbH,86666,DE,DAP,2020-04-23,VRG-100079,True,2000.0,HELLMANN,Germany,56651,Deutschland,51.163818,10.447831
2373,2373,2020-04-29,VKAU-100001,PT. Bright International,16810,ID,PT. Bright International,16810,ID,CIF,2020-04-29,VRG-100094,False,5000.0,NaN,Indonesia,56651,Indonesia,-2.483383,117.890285

In [28]:
both1.drop(["Delivery_Country","Delivery_Postal_Code2","Outgoing_goods_date","Outgoing_goods_date","Customer_Delivery_address_name"],axis=1, inplace=True)

In [30]:
both1

,Unnamed: 0,Booking_date,Order_number,Customer_name,Customer_postal_code,Delivery_country_name,Delivery_Terms,Invoice_N,lesser than 3tonnes,Quantity_kg,Shipping_agent,Delivery_Country_,Point_of_pickup,Coordinates,latitude,longitude
0,0,2022-07-20,VKAU-102380,Möhlenkamp GmbH & Co. KG,26901,DE,DAP,VRG-102329,True,250.0,HELLMANN,Germany,56651,Deutschland,51.163818,10.447831
1,1,2022-07-21,VKAU-102382,Spezialfutter Neuruppin GmbH & Co. KG,16816,DE,DAP,NaN,False,NaN,NaN,Germany,56651,Deutschland,51.163818,10.447831
2,2,2022-07-18,VKAU-102379,Hoogland BV,8903 JN,NL,DAP,NaN,False,NaN,NaN,Netherland,56651,"Netherland, Greatland Subdivision, San Pedro, ...",14.351639,121.050114
3,3,2022-07-18,VKAU-102378,Tromp B.V.,8912 AT,NL,DAP,NaN,False,NaN,NaN,Netherland,56651,"Netherland, Greatland Subdivision, San Pedro, ...",14.351639,121.050114
4,4,2022-07-15,VKAU-102377,Xaver Scheule GmbH,87757,DE,DAP,NaN,False,NaN,NaN,Germany,56651,Deutschland,51.163818,10.447831
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2369,2369,2020-04-07,VKAU-100005,TKF Korpas LLC,129515,RU,FCA,VRG-100027,True,1000.0,NaN,Russia,56651,Россия,64.686314,97.745306
2370,2370,2020-04-17,VKAU-100004,Kubbar International Company,11936,EG,CIF,VRG-100054,True,0.0,NaN,Egypt,56651,مصر,26.254049,29.267547
2371,2371,2020-04-30,VKAU-100003,EugeneBio,16697,KR,CIF,VRG-100098,False,10000.0,LESCHACO,Korea,56651,대한민국,36.638392,127.696119
2372,2372,2020-04-27,VKAU-100002,Trouw Nutrition Deutschland GmbH,86666,DE,DAP,VRG-100079,True,2000.0,HELLMANN,Germany,56651,Deutschland,51.163818,10.447831
2373,2373,2020-04-29,VKAU-100001,PT. Bright International,16810,ID,CIF,VRG-100094,False,5000.0,NaN,Indonesia,56651,Indonesia,-2.483383,117.890285

In [31]:
both1["Pickup station"]= "Im Stiefelfeld 10, 56651 Neiderzissen, Germany"
both1

,Unnamed: 0,Booking_date,Order_number,Customer_name,Customer_postal_code,Delivery_country_name,Delivery_Terms,Invoice_N,lesser than 3tonnes,Quantity_kg,Shipping_agent,Delivery_Country_,Point_of_pickup,Coordinates,latitude,longitude,Pickup station
0,0,2022-07-20,VKAU-102380,Möhlenkamp GmbH & Co. KG,26901,DE,DAP,VRG-102329,True,250.0,HELLMANN,Germany,56651,Deutschland,51.163818,10.447831,"Im Stiefelfeld 10, 56651 Neiderzissen, Germany"
1,1,2022-07-21,VKAU-102382,Spezialfutter Neuruppin GmbH & Co. KG,16816,DE,DAP,NaN,False,NaN,NaN,Germany,56651,Deutschland,51.163818,10.447831,"Im Stiefelfeld 10, 56651 Neiderzissen, Germany"
2,2,2022-07-18,VKAU-102379,Hoogland BV,8903 JN,NL,DAP,NaN,False,NaN,NaN,Netherland,56651,"Netherland, Greatland Subdivision, San Pedro, ...",14.351639,121.050114,"Im Stiefelfeld 10, 56651 Neiderzissen, Germany"
3,3,2022-07-18,VKAU-102378,Tromp B.V.,8912 AT,NL,DAP,NaN,False,NaN,NaN,Netherland,56651,"Netherland, Greatland Subdivision, San Pedro, ...",14.351639,121.050114,"Im Stiefelfeld 10, 56651 Neiderzissen, Germany"
4,4,2022-07-15,VKAU-102377,Xaver Scheule GmbH,87757,DE,DAP,NaN,False,NaN,NaN,Germany,56651,Deutschland,51.163818,10.447831,"Im Stiefelfeld 10, 56651 Neiderzissen, Germany"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2369,2369,2020-04-07,VKAU-100005,TKF Korpas LLC,129515,RU,FCA,VRG-100027,True,1000.0,NaN,Russia,56651,Россия,64.686314,97.745306,"Im Stiefelfeld 10, 56651 Neiderzissen, Germany"
2370,2370,2020-04-17,VKAU-100004,Kubbar International Company,11936,EG,CIF,VRG-100054,True,0.0,NaN,Egypt,56651,مصر,26.254049,29.267547,"Im Stiefelfeld 10, 56651 Neiderzissen, Germany"
2371,2371,2020-04-30,VKAU-100003,EugeneBio,16697,KR,CIF,VRG-100098,False,10000.0,LESCHACO,Korea,56651,대한민국,36.638392,127.696119,"Im Stiefelfeld 10, 56651 Neiderzissen, Germany"
2372,2372,2020-04-27,VKAU-100002,Trouw Nutrition Deutschland GmbH,86666,DE,DAP,VRG-100079,True,2000.0,HELLMANN,Germany,56651,Deutschland,51.163818,10.447831,"Im Stiefelfeld 10, 56651 Neiderzissen, Germany"
2373,2373,2020-04-29,VKAU-100001,PT. Bright International,16810,ID,CIF,VRG-100094,False,5000.0,NaN,Indonesia,56651,Indonesia,-2.483383,117.890285,"Im Stiefelfeld 10, 56651 Neiderzissen, Germany"

In [5]:
pip install geocoder

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting geocoder
  Downloading geocoder-1.38.1-py2.py3-none-any.whl (98 kB)
     |████████████████████████████████| 98 kB 6.8 MB/s
Requirement already satisfied: click in /usr/local/lib/python3.7/dist-packages (from geocoder) (7.1.2)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from geocoder) (1.15.0)
Collecting ratelim
  Downloading ratelim-0.1.6-py2.py3-none-any.whl (4.0 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from geocoder) (2.23.0)
Requirement already satisfied: future in /usr/local/lib/python3.7/dist-packages (from geocoder) (0.16.0)
Requirement already satisfied: decorator in /usr/local/lib/python3.7/dist-packages (from ratelim->geocoder) (4.4.2)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->geocoder) (2022.6.15)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->geocoder) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->geocoder) (1.24.3)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->geocoder) (3.0.4)
Installing collected packages: ratelim, geocoder
Successfully installed geocoder-1.38.1 ratelim-0.1.6

In [7]:
from geopy.geocoders import Nominatim
from geopy import distance

In [11]:
from geopy import geocoders
geocoders.Nominatim(user_agent="colab")

In [12]:
location1=
location2=

SyntaxError: ignored